package bean;
// Generated 15/09/2023 18:51:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClienteFgv generated by hbm2java
 */
@Entity
@Table(name="cliente_fgv"
    ,catalog="db_felipe_ronceti"
)
public class ClienteFgv  implements java.io.Serializable {


     private int idclienteFgv;
     private String apelidoFgv;
     private String bairroFgv;
     private String cepFgv;
     private String cnpjFgv;
     private String cpfFgv;
     private String emailFgv;
     private String enderecoFgv;
     private String estadocivilFgv;
     private String nacionalidadeFgv;
     private String nomeFgv;
     private String rgFgv;
     private String sexoFgv;
     private String telefoneFgv;
     private String ufFgv;

    public ClienteFgv() {
    }

    public ClienteFgv(int idclienteFgv, String apelidoFgv, String bairroFgv, String cepFgv, String cnpjFgv, String cpfFgv, String emailFgv, String enderecoFgv, String estadocivilFgv, String nacionalidadeFgv, String nomeFgv, String rgFgv, String sexoFgv, String telefoneFgv, String ufFgv) {
       this.idclienteFgv = idclienteFgv;
       this.apelidoFgv = apelidoFgv;
       this.bairroFgv = bairroFgv;
       this.cepFgv = cepFgv;
       this.cnpjFgv = cnpjFgv;
       this.cpfFgv = cpfFgv;
       this.emailFgv = emailFgv;
       this.enderecoFgv = enderecoFgv;
       this.estadocivilFgv = estadocivilFgv;
       this.nacionalidadeFgv = nacionalidadeFgv;
       this.nomeFgv = nomeFgv;
       this.rgFgv = rgFgv;
       this.sexoFgv = sexoFgv;
       this.telefoneFgv = telefoneFgv;
       this.ufFgv = ufFgv;
    }
   
     @Id 

    
    @Column(name="idcliente_fgv", unique=true, nullable=false)
    public int getIdclienteFgv() {
        return this.idclienteFgv;
    }
    
    public void setIdclienteFgv(int idclienteFgv) {
        this.idclienteFgv = idclienteFgv;
    }

    
    @Column(name="apelido_fgv", nullable=false, length=50)
    public String getApelidoFgv() {
        return this.apelidoFgv;
    }
    
    public void setApelidoFgv(String apelidoFgv) {
        this.apelidoFgv = apelidoFgv;
    }

    
    @Column(name="bairro_fgv", nullable=false, length=100)
    public String getBairroFgv() {
        return this.bairroFgv;
    }
    
    public void setBairroFgv(String bairroFgv) {
        this.bairroFgv = bairroFgv;
    }

    
    @Column(name="cep_fgv", nullable=false, length=10)
    public String getCepFgv() {
        return this.cepFgv;
    }
    
    public void setCepFgv(String cepFgv) {
        this.cepFgv = cepFgv;
    }

    
    @Column(name="cnpj_fgv", nullable=false, length=18)
    public String getCnpjFgv() {
        return this.cnpjFgv;
    }
    
    public void setCnpjFgv(String cnpjFgv) {
        this.cnpjFgv = cnpjFgv;
    }

    
    @Column(name="cpf_fgv", nullable=false, length=11)
    public String getCpfFgv() {
        return this.cpfFgv;
    }
    
    public void setCpfFgv(String cpfFgv) {
        this.cpfFgv = cpfFgv;
    }

    
    @Column(name="email_fgv", nullable=false, length=80)
    public String getEmailFgv() {
        return this.emailFgv;
    }
    
    public void setEmailFgv(String emailFgv) {
        this.emailFgv = emailFgv;
    }

    
    @Column(name="endereco_fgv", nullable=false, length=60)
    public String getEnderecoFgv() {
        return this.enderecoFgv;
    }
    
    public void setEnderecoFgv(String enderecoFgv) {
        this.enderecoFgv = enderecoFgv;
    }

    
    @Column(name="estadocivil_fgv", nullable=false, length=20)
    public String getEstadocivilFgv() {
        return this.estadocivilFgv;
    }
    
    public void setEstadocivilFgv(String estadocivilFgv) {
        this.estadocivilFgv = estadocivilFgv;
    }

    
    @Column(name="nacionalidade_fgv", nullable=false, length=45)
    public String getNacionalidadeFgv() {
        return this.nacionalidadeFgv;
    }
    
    public void setNacionalidadeFgv(String nacionalidadeFgv) {
        this.nacionalidadeFgv = nacionalidadeFgv;
    }

    
    @Column(name="nome_fgv", nullable=false, length=20)
    public String getNomeFgv() {
        return this.nomeFgv;
    }
    
    public void setNomeFgv(String nomeFgv) {
        this.nomeFgv = nomeFgv;
    }

    
    @Column(name="rg_fgv", nullable=false, length=30)
    public String getRgFgv() {
        return this.rgFgv;
    }
    
    public void setRgFgv(String rgFgv) {
        this.rgFgv = rgFgv;
    }

    @Column(name="sexo_fgv", nullable=false, length=1)
    public String getSexoFgv() {
        return this.sexoFgv;
    }
    
    public void setSexoFgv(String rgFgv) {
        this.sexoFgv = sexoFgv;
    }

    
    @Column(name="telefone_fgv", nullable=false, length=14)
    public String getTelefoneFgv() {
        return this.telefoneFgv;
    }
    
    public void setTelefoneFgv(String telefoneFgv) {
        this.telefoneFgv = telefoneFgv;
    }

    
    @Column(name="uf_fgv", nullable=false, length=2)
    public String getUfFgv() {
        return this.ufFgv;
    }
    
    public void setUfFgv(String ufFgv) {
        this.ufFgv = ufFgv;
    }




}


