package bean;
// Generated 15/09/2023 18:51:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CompraprodutoFgv generated by hbm2java
 */
@Entity
@Table(name="compraproduto_fgv"
    ,catalog="db_felipe_ronceti"
)
public class CompraprodutoFgv  implements java.io.Serializable {


     private CompraprodutoFgvId id;
     private String nomeprodutoFgv;
     private String quantidadeFgv;
     private BigDecimal valorcompraprodutoFgv;

    public CompraprodutoFgv() {
    }

    public CompraprodutoFgv(CompraprodutoFgvId id, String nomeprodutoFgv, String quantidadeFgv, BigDecimal valorcompraprodutoFgv) {
       this.id = id;
       this.nomeprodutoFgv = nomeprodutoFgv;
       this.quantidadeFgv = quantidadeFgv;
       this.valorcompraprodutoFgv = valorcompraprodutoFgv;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcompraFgv", column=@Column(name="idcompra_fgv", nullable=false) ), 
        @AttributeOverride(name="idcompraprodutoFgv", column=@Column(name="idcompraproduto_fgv", nullable=false) ), 
        @AttributeOverride(name="idprodutoFgv", column=@Column(name="idproduto_fgv", nullable=false) ) } )
    public CompraprodutoFgvId getId() {
        return this.id;
    }
    
    public void setId(CompraprodutoFgvId id) {
        this.id = id;
    }

    
    @Column(name="nomeproduto_fgv", nullable=false, length=45)
    public String getNomeprodutoFgv() {
        return this.nomeprodutoFgv;
    }
    
    public void setNomeprodutoFgv(String nomeprodutoFgv) {
        this.nomeprodutoFgv = nomeprodutoFgv;
    }

    
    @Column(name="quantidade_fgv", nullable=false, length=10)
    public String getQuantidadeFgv() {
        return this.quantidadeFgv;
    }
    
    public void setQuantidadeFgv(String quantidadeFgv) {
        this.quantidadeFgv = quantidadeFgv;
    }

    
    @Column(name="valorcompraproduto_fgv", nullable=false, precision=10, scale=0)
    public BigDecimal getValorcompraprodutoFgv() {
        return this.valorcompraprodutoFgv;
    }
    
    public void setValorcompraprodutoFgv(BigDecimal valorcompraprodutoFgv) {
        this.valorcompraprodutoFgv = valorcompraprodutoFgv;
    }




}


