package bean;
// Generated 15/09/2023 18:51:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompraprodutoFgvId generated by hbm2java
 */
@Embeddable
public class CompraprodutoFgvId  implements java.io.Serializable {


     private int idcompraFgv;
     private int idcompraprodutoFgv;
     private int idprodutoFgv;

    public CompraprodutoFgvId() {
    }

    public CompraprodutoFgvId(int idcompraFgv, int idcompraprodutoFgv, int idprodutoFgv) {
       this.idcompraFgv = idcompraFgv;
       this.idcompraprodutoFgv = idcompraprodutoFgv;
       this.idprodutoFgv = idprodutoFgv;
    }
   


    @Column(name="idcompra_fgv", nullable=false)
    public int getIdcompraFgv() {
        return this.idcompraFgv;
    }
    
    public void setIdcompraFgv(int idcompraFgv) {
        this.idcompraFgv = idcompraFgv;
    }


    @Column(name="idcompraproduto_fgv", nullable=false)
    public int getIdcompraprodutoFgv() {
        return this.idcompraprodutoFgv;
    }
    
    public void setIdcompraprodutoFgv(int idcompraprodutoFgv) {
        this.idcompraprodutoFgv = idcompraprodutoFgv;
    }


    @Column(name="idproduto_fgv", nullable=false)
    public int getIdprodutoFgv() {
        return this.idprodutoFgv;
    }
    
    public void setIdprodutoFgv(int idprodutoFgv) {
        this.idprodutoFgv = idprodutoFgv;
    }




}


