package bean;
// Generated 15/09/2023 18:51:11 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CompraFgv generated by hbm2java
 */
@Entity
@Table(name="compra_fgv"
    ,catalog="db_felipe_ronceti"
)
public class CompraFgv  implements java.io.Serializable {


     private int idcompraFgv;
     private String nomeclienteFgv;
     private short quantidadeFgv;
     private String statusFgv;
     private BigDecimal valorcompraFgv;

    public CompraFgv() {
    }

    public CompraFgv(int idcompraFgv, String nomeclienteFgv, short quantidadeFgv, String statusFgv, BigDecimal valorcompraFgv) {
       this.idcompraFgv = idcompraFgv;
       this.nomeclienteFgv = nomeclienteFgv;
       this.quantidadeFgv = quantidadeFgv;
       this.statusFgv = statusFgv;
       this.valorcompraFgv = valorcompraFgv;
    }
   
     @Id 

    
    @Column(name="idcompra_fgv", unique=true, nullable=false)
    public int getIdcompraFgv() {
        return this.idcompraFgv;
    }
    
    public void setIdcompraFgv(int idcompraFgv) {
        this.idcompraFgv = idcompraFgv;
    }

    
    @Column(name="nomecliente_fgv", nullable=false, length=45)
    public String getNomeclienteFgv() {
        return this.nomeclienteFgv;
    }
    
    public void setNomeclienteFgv(String nomeclienteFgv) {
        this.nomeclienteFgv = nomeclienteFgv;
    }

    
    @Column(name="quantidade_fgv", nullable=false)
    public short getQuantidadeFgv() {
        return this.quantidadeFgv;
    }
    
    public void setQuantidadeFgv(short quantidadeFgv) {
        this.quantidadeFgv = quantidadeFgv;
    }

    
    @Column(name="status_fgv", nullable=false, length=45)
    public String getStatusFgv() {
        return this.statusFgv;
    }
    
    public void setStatusFgv(String statusFgv) {
        this.statusFgv = statusFgv;
    }

    
    @Column(name="valorcompra_fgv", nullable=false, precision=8, scale=0)
    public BigDecimal getValorcompraFgv() {
        return this.valorcompraFgv;
    }
    
    public void setValorcompraFgv(BigDecimal valorcompraFgv) {
        this.valorcompraFgv = valorcompraFgv;
    }




}


