package bean;
// Generated 15/09/2023 18:51:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioFgv generated by hbm2java
 */
@Entity
@Table(name="usuario_fgv"
    ,catalog="db_felipe_ronceti"
)
public class UsuarioFgv  implements java.io.Serializable {


     private int idusuarioFgv;
     private String apelidoFgv;
     private String ativoFgv;
     private String cpfFgv;
     private Date datanascimentoFgv;
     private String nivelFgv;
     private String nomeFgv;
     private String senhaFgv;

    public UsuarioFgv() {
    }

    public UsuarioFgv(int idusuarioFgv, String apelidoFgv, String ativoFgv, String cpfFgv, Date datanascimentoFgv, String nivelFgv, String nomeFgv, String senhaFgv) {
       this.idusuarioFgv = idusuarioFgv;
       this.apelidoFgv = apelidoFgv;
       this.ativoFgv = ativoFgv;
       this.cpfFgv = cpfFgv;
       this.datanascimentoFgv = datanascimentoFgv;
       this.nivelFgv = nivelFgv;
       this.nomeFgv = nomeFgv;
       this.senhaFgv = senhaFgv;
    }
   
     @Id 

    
    @Column(name="idusuario_fgv", unique=true, nullable=false)
    public int getIdusuarioFgv() {
        return this.idusuarioFgv;
    }
    
    public void setIdusuarioFgv(int idusuarioFgv) {
        this.idusuarioFgv = idusuarioFgv;
    }

    
    @Column(name="apelido_fgv", nullable=false, length=45)
    public String getApelidoFgv() {
        return this.apelidoFgv;
    }
    
    public void setApelidoFgv(String apelidoFgv) {
        this.apelidoFgv = apelidoFgv;
    }

    
    @Column(name="ativo_fgv", nullable=false, length=45)
    public String getAtivoFgv() {
        return this.ativoFgv;
    }
    
    public void setAtivoFgv(String ativoFgv) {
        this.ativoFgv = ativoFgv;
    }

    
    @Column(name="cpf_fgv", nullable=false, length=11)
    public String getCpfFgv() {
        return this.cpfFgv;
    }
    
    public void setCpfFgv(String cpfFgv) {
        this.cpfFgv = cpfFgv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datanascimento_fgv", nullable=false, length=10)
    public Date getDatanascimentoFgv() {
        return this.datanascimentoFgv;
    }
    
    public void setDatanascimentoFgv(Date datanascimentoFgv) {
        this.datanascimentoFgv = datanascimentoFgv;
    }

    
    @Column(name="nivel_fgv", nullable=false, length=10)
    public String getNivelFgv() {
        return this.nivelFgv;
    }
    
    public void setNivelFgv(String nivelFgv) {
        this.nivelFgv = nivelFgv;
    }

    
    @Column(name="nome_fgv", nullable=false, length=45)
    public String getNomeFgv() {
        return this.nomeFgv;
    }
    
    public void setNomeFgv(String nomeFgv) {
        this.nomeFgv = nomeFgv;
    }

    
    @Column(name="senha_fgv", nullable=false, length=45)
    public String getSenhaFgv() {
        return this.senhaFgv;
    }
    
    public void setSenhaFgv(String senhaFgv) {
        this.senhaFgv = senhaFgv;
    }




}


